version: '3.5'

services:
  spiritus-web:
    container_name: spiritus-web
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "8080:3000"
    environment:
      - NEXT_API_URL=${NEXT_API_URL}
      - NEXT_JWT_SECRET=${NEXT_JWT_SECRET}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXT_NODE_ENV=${NEXT_NODE_ENV}
