version: '3.5'

services:
  spiritus-web:
    container_name: spiritus-web
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:3000"
    environment:
      - NEXT_NODE_ENV=development
      - NEXTAUTH_URL=http://localhost:3000
      - NEXT_API_URL=https://walk.spiritusapp.com
      - NEXT_JWT_SECRET=muchsecrets
      - NEXTAUTH_SECRET=justanotherverysecretvalue
