version: '3.5'

services:
  spiritus-web:
    container_name: spiritus-web
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_NODE_ENV=production
      - NEXTAUTH_URL=http://localhost:3000
      - NEXT_API_URL=${NEXT_API_URL}
      - NEXT_JWT_SECRET=${NEXT_JWT_SECRET}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
