export const MockResponse = {
  homeListItems: [
    {
      id: 1,
      viewType: "FEATURED",
      title: null,
      state: null,
      subtitle: null,
      flags: ["FEATURED_SECTION"],
      listPayload: null,
      version: "1",
      items: {
        content: [
          {
            id: 1,
            title: "Priča dana",
            subtitle: "Dino Dvornik",
            placeholderText: "O ludim tinejdžerskim provodima.",
            actionButtonText: "Pročitajte",
            negativeActionButtonText: null,
            parentId: "74373",
            parentNavigationType: "SPIRITUS_DETAILS",
            itemId: "259",
            itemNavigationType: "STORY_DETAILS",
            itemPayload: null,
            imageUrl: "/images/89121/spiritus",
            flags: [],
          },
        ],
        pageable: {
          sort: {
            sorted: false,
            unsorted: true,
            empty: true,
          },
          offset: 0,
          pageNumber: 0,
          pageSize: 1,
          paged: true,
          unpaged: false,
        },
        last: true,
        totalElements: 1,
        totalPages: 1,
        size: 1,
        number: 0,
        sort: {
          sorted: false,
          unsorted: true,
          empty: true,
        },
        first: true,
        numberOfElements: 1,
        empty: false,
      },
    },
    {
      id: 47,
      viewType: "SINGLE_INFO",
      title: null,
      state: null,
      subtitle: null,
      flags: ["FUNERAL_NOTICE"],
      listPayload: null,
      version: null,
      items: {
        content: [
          {
            id: 10,
            title: "Obavijesti",
            subtitle: "Pogledajte tko je nedavno preminuo.",
            placeholderText: null,
            actionButtonText: null,
            negativeActionButtonText: null,
            parentId: "null",
            parentNavigationType: null,
            itemId: "null",
            itemNavigationType: "FUNERAL_NOTICE",
            itemPayload: null,
            imageUrl: null,
            flags: ["FUNERAL_NOTICE"],
          },
        ],
        pageable: {
          sort: {
            sorted: false,
            unsorted: true,
            empty: true,
          },
          offset: 0,
          pageNumber: 0,
          pageSize: 1,
          paged: true,
          unpaged: false,
        },
        last: true,
        totalElements: 1,
        totalPages: 1,
        size: 1,
        number: 0,
        sort: {
          sorted: false,
          unsorted: true,
          empty: true,
        },
        first: true,
        numberOfElements: 1,
        empty: false,
      },
    },
    {
      id: 48,
      viewType: "SINGLE_INFO",
      title: null,
      state: null,
      subtitle: null,
      flags: ["FUNERAL_PARTNERS"],
      listPayload: null,
      version: null,
      items: {
        content: [
          {
            id: 11,
            title: "Suradnici",
            subtitle: "Pogledajte naše suradnike.",
            placeholderText: null,
            actionButtonText: null,
            negativeActionButtonText: null,
            parentId: "null",
            parentNavigationType: null,
            itemId: "null",
            itemNavigationType: "FUNERAL_PARTNERS",
            itemPayload: null,
            imageUrl: null,
            flags: ["FUNERAL_PARTNERS"],
          },
        ],
        pageable: {
          sort: {
            sorted: false,
            unsorted: true,
            empty: true,
          },
          offset: 0,
          pageNumber: 0,
          pageSize: 1,
          paged: true,
          unpaged: false,
        },
        last: true,
        totalElements: 1,
        totalPages: 1,
        size: 1,
        number: 0,
        sort: {
          sorted: false,
          unsorted: true,
          empty: true,
        },
        first: true,
        numberOfElements: 1,
        empty: false,
      },
    },
    {
      id: 79,
      viewType: "MEDIUM",
      title: "Novi",
      state: null,
      subtitle: "Novi memorijali",
      flags: ["SHOW_ALL", "NEW_SECTION"],
      listPayload: null,
      version: "1",
      items: {
        content: [
          {
            id: 647496,
            title: "dsfasd dasfsd",
            subtitle: "06 Jul 2023 — 12 Jul 2023",
            placeholderText: null,
            actionButtonText: null,
            negativeActionButtonText: null,
            parentId: null,
            parentNavigationType: null,
            itemId: "dsfasd-dasfsd-51c2aefe",
            itemNavigationType: "SPIRITUS_DETAILS",
            itemPayload: null,
            imageUrl: "/images/89907/spiritus",
            flags: [],
          },
          {
            id: 647495,
            title: "Dinina Ping Pong Vladavina",
            subtitle: "21 Jun 2023 — 06 Jul 2023",
            placeholderText: null,
            actionButtonText: null,
            negativeActionButtonText: null,
            parentId: null,
            parentNavigationType: null,
            itemId: "dinina-ping-pong-vladavina-46d88fb4",
            itemNavigationType: "SPIRITUS_DETAILS",
            itemPayload: null,
            imageUrl: "/images/89906/spiritus",
            flags: [],
          },
          {
            id: 647491,
            title: "VINKO DINKO",
            subtitle: "01 Jun 2023 — 02 Jun 2023",
            placeholderText: "Nemamo svoje mapbox tokene",
            actionButtonText: null,
            negativeActionButtonText: null,
            parentId: null,
            parentNavigationType: null,
            itemId: "vinko-dinko-0f6b6c7b",
            itemNavigationType: "SPIRITUS_DETAILS",
            itemPayload: null,
            imageUrl: "/images/89898/spiritus",
            flags: [],
          },
          {
            id: 647490,
            title: "d cx",
            subtitle: "? — ?",
            placeholderText: null,
            actionButtonText: null,
            negativeActionButtonText: null,
            parentId: null,
            parentNavigationType: null,
            itemId: "d-cx-8de46758",
            itemNavigationType: "SPIRITUS_DETAILS",
            itemPayload: null,
            imageUrl: "/images/89897/spiritus",
            flags: [],
          },
          {
            id: 647488,
            title: "Ime Prezime",
            subtitle: "12 Jun 2023 — 12 Jun 2023",
            placeholderText: null,
            actionButtonText: null,
            negativeActionButtonText: null,
            parentId: null,
            parentNavigationType: null,
            itemId: "ime-prezime-386a42f3",
            itemNavigationType: "SPIRITUS_DETAILS",
            itemPayload: null,
            imageUrl: "/images/89896/spiritus",
            flags: [],
          },
          {
            id: 647487,
            title: "Create test Test cto",
            subtitle: "23 May 2023 — 23 May 2023",
            placeholderText: "",
            actionButtonText: null,
            negativeActionButtonText: null,
            parentId: null,
            parentNavigationType: null,
            itemId: "create-test-test-cto-758d7909",
            itemNavigationType: "SPIRITUS_DETAILS",
            itemPayload: null,
            imageUrl: "/images/89894/spiritus",
            flags: [],
          },
          {
            id: 647486,
            title: "Mufinjo Tester CTO Tester",
            subtitle: "23 May 2018 — 23 May 2023",
            placeholderText: "Description",
            actionButtonText: null,
            negativeActionButtonText: null,
            parentId: null,
            parentNavigationType: null,
            itemId: "mufinjo-tester-cto-tester-c6d230a4",
            itemNavigationType: "SPIRITUS_DETAILS",
            itemPayload: null,
            imageUrl: "/images/89892/spiritus",
            flags: [],
          },
          {
            id: 647485,
            title: "Mufinjo Tester CTO Tester",
            subtitle: "23 May 2018 — 23 May 2023",
            placeholderText: "Description",
            actionButtonText: null,
            negativeActionButtonText: null,
            parentId: null,
            parentNavigationType: null,
            itemId: "mufinjo-tester-cto-tester-d343e0d2",
            itemNavigationType: "SPIRITUS_DETAILS",
            itemPayload: null,
            imageUrl: "/images/89890/spiritus",
            flags: [],
          },
          {
            id: 647484,
            title: "Spiritus Create Test Spiritus Create Test",
            subtitle: "16 May 2023 — 25 May 2023",
            placeholderText: "",
            actionButtonText: null,
            negativeActionButtonText: null,
            parentId: null,
            parentNavigationType: null,
            itemId: "spiritus-create-test-spiritus-create-test-19dbae1a",
            itemNavigationType: "SPIRITUS_DETAILS",
            itemPayload: null,
            imageUrl: "/images/89888/spiritus",
            flags: [],
          },
          {
            id: 647483,
            title: "Novi Test Novi Test",
            subtitle: "23 May 2023 — 16 May 2023",
            placeholderText: "",
            actionButtonText: null,
            negativeActionButtonText: null,
            parentId: null,
            parentNavigationType: null,
            itemId: "novi-test-novi-test-490976ee",
            itemNavigationType: "SPIRITUS_DETAILS",
            itemPayload: null,
            imageUrl: "/images/89887/spiritus",
            flags: [],
          },
        ],
        pageable: {
          sort: {
            sorted: false,
            unsorted: true,
            empty: true,
          },
          offset: 0,
          pageNumber: 0,
          pageSize: 10,
          paged: true,
          unpaged: false,
        },
        last: false,
        totalElements: 511551,
        totalPages: 51156,
        size: 10,
        number: 0,
        sort: {
          sorted: false,
          unsorted: true,
          empty: true,
        },
        first: true,
        numberOfElements: 10,
        empty: false,
      },
    },
    {
      id: 4,
      viewType: "LARGE",
      title: "Godišnjice",
      state: null,
      subtitle: null,
      flags: ["SHOW_ALL", "ANNIVERSARIES_SECTION"],
      listPayload: null,
      version: "1",
      items: {
        content: [
          {
            id: 11572,
            title: "Vera Spudić",
            subtitle: "28 Jan 1948 — 08 Jul 2020",
            placeholderText: "Žena, majka, kraljica",
            actionButtonText: null,
            negativeActionButtonText: null,
            parentId: null,
            parentNavigationType: null,
            itemId: "vera-spudic-7ac3c2a8",
            itemNavigationType: "SPIRITUS_DETAILS",
            itemPayload: null,
            imageUrl: "/images/15020/spiritus",
            flags: [],
          },
          {
            id: 11721,
            title: "Marija  Marinac",
            subtitle: "08 Jan 1942 — 09 Jul 2021",
            placeholderText: "Baka koja je uvijek ispunjavala želje.",
            actionButtonText: null,
            negativeActionButtonText: null,
            parentId: null,
            parentNavigationType: null,
            itemId: "marija--marinac-d2499e94",
            itemNavigationType: "SPIRITUS_DETAILS",
            itemPayload: null,
            imageUrl: "/images/12630/spiritus",
            flags: [],
          },
          {
            id: 9810,
            title: "Željko Malnar",
            subtitle: "12 Apr 1944 — 09 Jul 2013",
            placeholderText: "Predsjednik Republika Pešćenice",
            actionButtonText: null,
            negativeActionButtonText: null,
            parentId: null,
            parentNavigationType: null,
            itemId: "zeljko-malnar-3e029742",
            itemNavigationType: "SPIRITUS_DETAILS",
            itemPayload: null,
            imageUrl: "/images/9812/spiritus",
            flags: [],
          },
          {
            id: 1228,
            title: "Kata Merdita",
            subtitle: "09 Jul 1935 — 09 Jul 2007",
            placeholderText: "Spirits are everywhere and God is listening.",
            actionButtonText: null,
            negativeActionButtonText: null,
            parentId: null,
            parentNavigationType: null,
            itemId: "kata-merdita-5d3acbf8",
            itemNavigationType: "SPIRITUS_DETAILS",
            itemPayload: null,
            imageUrl: "/images/1244/spiritus",
            flags: [],
          },
          {
            id: 647465,
            title: "Matija 5barhjtfjgjgj",
            subtitle: "11 Jul 1994 — 11 Jul 1994",
            placeholderText: "",
            actionButtonText: null,
            negativeActionButtonText: null,
            parentId: null,
            parentNavigationType: null,
            itemId: "matija-5rtf-bdb678b6",
            itemNavigationType: "SPIRITUS_DETAILS",
            itemPayload: null,
            imageUrl: "/images/89875/spiritus",
            flags: [],
          },
          {
            id: 87411,
            title: "Ljubomir Komlenić",
            subtitle: "26 Mar 1959 — 12 Jul 2009",
            placeholderText: "Profesionalan i galantan",
            actionButtonText: null,
            negativeActionButtonText: null,
            parentId: null,
            parentNavigationType: null,
            itemId: "ljubomir-komlenic-0033eadb",
            itemNavigationType: "SPIRITUS_DETAILS",
            itemPayload: null,
            imageUrl: "/images/87413/spiritus",
            flags: [],
          },
          {
            id: 19881,
            title: "Blagica Crnjac",
            subtitle: "14 Aug 1934 — 12 Jul 1999",
            placeholderText: "TETKA iz Njemačke",
            actionButtonText: null,
            negativeActionButtonText: null,
            parentId: null,
            parentNavigationType: null,
            itemId: "blagica-crnjac-c90ed211",
            itemNavigationType: "SPIRITUS_DETAILS",
            itemPayload: null,
            imageUrl: "/images/19883/spiritus",
            flags: [],
          },
          {
            id: 113916,
            title: "Stjepan Valdec",
            subtitle: "18 Nov 1829 — 13 Jul 1921",
            placeholderText: "Ponositi Varaždinac, svećenik i ratnik.",
            actionButtonText: null,
            negativeActionButtonText: null,
            parentId: null,
            parentNavigationType: null,
            itemId: "stjepan-valdec-a53fb672",
            itemNavigationType: "SPIRITUS_DETAILS",
            itemPayload: null,
            imageUrl: "/images/89491/spiritus",
            flags: [],
          },
          {
            id: 89146,
            title: "Antun Stöhr",
            subtitle: "09 Sep 1847 — 13 Jul 1923",
            placeholderText:
              "Varaždinski skladatelj i voljeni glazbeni pedagog.",
            actionButtonText: null,
            negativeActionButtonText: null,
            parentId: null,
            parentNavigationType: null,
            itemId: "antun-stohr-fd60b6e8",
            itemNavigationType: "SPIRITUS_DETAILS",
            itemPayload: null,
            imageUrl: "/images/89487/spiritus",
            flags: [],
          },
          {
            id: 13235,
            title: "Marko Kocic",
            subtitle: "23 Feb 1920 — 14 Jul 1992",
            placeholderText: "Najbolji dida na cijelom svijetu....",
            actionButtonText: null,
            negativeActionButtonText: null,
            parentId: null,
            parentNavigationType: null,
            itemId: "marko-kocic-0811091e",
            itemNavigationType: "SPIRITUS_DETAILS",
            itemPayload: null,
            imageUrl: "/images/20226/spiritus",
            flags: [],
          },
        ],
        pageable: {
          sort: {
            sorted: false,
            unsorted: true,
            empty: true,
          },
          offset: 0,
          pageNumber: 0,
          pageSize: 10,
          paged: true,
          unpaged: false,
        },
        last: false,
        totalElements: 48,
        totalPages: 5,
        size: 10,
        number: 0,
        sort: {
          sorted: false,
          unsorted: true,
          empty: true,
        },
        first: true,
        numberOfElements: 10,
        empty: false,
      },
    },
    {
      id: 46,
      viewType: "FEATURED",
      title: null,
      state: null,
      subtitle: null,
      flags: ["PROJECTS_SECTION"],
      listPayload: null,
      version: null,
      items: {
        content: [
          {
            id: 9,
            title: "PROJEKT",
            subtitle: "Vječno Hvala",
            placeholderText: null,
            actionButtonText: "Saznaj više",
            negativeActionButtonText: null,
            parentId: "null",
            parentNavigationType: null,
            itemId: "null",
            itemNavigationType: "SHOW_ALL",
            itemPayload:
              '{"description":"Svaki je ljudski život mnogo više od imena i datuma. Vječno Hvala je projekt u kojemu prikupljamo uspomene na žrtve Domovinskog rata.\n\nAko ste poznavali naše heroje, postanite njihov Čuvar Uspomena. Postavite fotografije, anegdote i životne priče po kojima ćemo ih pamtiti, vječno."}',
            imageUrl: "/images/2/item",
            flags: ["PROJECT_VUKOVAR"],
          },
        ],
        pageable: {
          sort: {
            sorted: false,
            unsorted: true,
            empty: true,
          },
          offset: 0,
          pageNumber: 0,
          pageSize: 1,
          paged: true,
          unpaged: false,
        },
        last: true,
        totalElements: 1,
        totalPages: 1,
        size: 1,
        number: 0,
        sort: {
          sorted: false,
          unsorted: true,
          empty: true,
        },
        first: true,
        numberOfElements: 1,
        empty: false,
      },
    },
    {
      id: 12,
      viewType: "BANNER",
      title: null,
      state: null,
      subtitle: null,
      flags: ["BANNERS_SECTION"],
      listPayload: null,
      version: "1",
      items: {
        content: [
          {
            id: 8,
            title: "Obljetnica je blizu!",
            subtitle: "Podsjetite se godišnjica Vaših najmilijih.",
            placeholderText: null,
            actionButtonText: "Uključite obavijesti",
            negativeActionButtonText: null,
            parentId: "null",
            parentNavigationType: null,
            itemId: "null",
            itemNavigationType: "ENABLE_NOTIFICATIONS",
            itemPayload: null,
            imageUrl: null,
            flags: [],
          },
        ],
        pageable: {
          sort: {
            sorted: false,
            unsorted: true,
            empty: true,
          },
          offset: 0,
          pageNumber: 0,
          pageSize: 1,
          paged: true,
          unpaged: false,
        },
        last: true,
        totalElements: 1,
        totalPages: 1,
        size: 1,
        number: 0,
        sort: {
          sorted: false,
          unsorted: true,
          empty: true,
        },
        first: true,
        numberOfElements: 1,
        empty: false,
      },
    },
    {
      id: 2,
      viewType: "LARGE",
      title: "Istraži priče",
      state: null,
      subtitle: null,
      flags: ["DISCOVERY_SECTION", "SHOW_ALL"],
      listPayload: null,
      version: "1",
      items: {
        content: [
          {
            id: 13368,
            title: 'Dvije polovice jednog srca,\n"Vratolomije dviju djevojaka"',
            subtitle: "Jadranka Makarić",
            placeholderText: "Najbolje od mene",
            actionButtonText: null,
            negativeActionButtonText: null,
            parentId: "jadranka-makaric-613695cf",
            parentNavigationType: "SPIRITUS_DETAILS",
            itemId:
              "dvije-polovice-jednog-srca-vratolomije-dviju-djevojaka-da40af6c",
            itemNavigationType: "STORY_DETAILS",
            itemPayload: null,
            imageUrl: "/images/13370/spiritus",
            flags: [],
          },
          {
            id: 88378,
            title: "Srebrni prsten i srce od zlata",
            subtitle: "Anka Tepšić",
            placeholderText:
              "Prije dvadeset godina iskopao sam prsten i poklonio ga baki, koja ga nikad nije skinula prsta.",
            actionButtonText: null,
            negativeActionButtonText: null,
            parentId: "anka-tepsic-add83bce",
            parentNavigationType: "SPIRITUS_DETAILS",
            itemId: "srebrni-prsten-i-srce-od-zlata-457469a3",
            itemNavigationType: "STORY_DETAILS",
            itemPayload: null,
            imageUrl: "/images/88380/spiritus",
            flags: [],
          },
          {
            id: 647470,
            title: "Name surname",
            subtitle: "Name Surname",
            placeholderText: "Name surname",
            actionButtonText: null,
            negativeActionButtonText: null,
            parentId: "name-surname-5d8819b6",
            parentNavigationType: "SPIRITUS_DETAILS",
            itemId: "name-surname-edd450ef",
            itemNavigationType: "STORY_DETAILS",
            itemPayload: null,
            imageUrl: "/images/1665/story",
            flags: [],
          },
          {
            id: 74373,
            title: "Crveni konji",
            subtitle: "Dino Dvornik",
            placeholderText: "O ludim tinejdžerskim provodima.",
            actionButtonText: null,
            negativeActionButtonText: null,
            parentId: "dino-dvornik-65a2e4af",
            parentNavigationType: "SPIRITUS_DETAILS",
            itemId: "crveni-konji-083ed63b",
            itemNavigationType: "STORY_DETAILS",
            itemPayload: null,
            imageUrl: "/images/880/story",
            flags: [],
          },
          {
            id: 70951,
            title: "Špilja Vindija",
            subtitle: "Stjepan Vuković",
            placeholderText:
              "– O moja spiljo Vindijo! Istražujući te punih 40 godina, pružila si mi mnogi lijepi užitak. Učila si me gledati slobodno smrti u oči... –",
            actionButtonText: null,
            negativeActionButtonText: null,
            parentId: "stjepan-vukovic-66e9983e",
            parentNavigationType: "SPIRITUS_DETAILS",
            itemId: "spilja-vindija-f4741981",
            itemNavigationType: "STORY_DETAILS",
            itemPayload: null,
            imageUrl: "/images/58/story",
            flags: [],
          },
          {
            id: 261386,
            title: "Mala Silva",
            subtitle: "Silva Uzorinac",
            placeholderText:
              "Silvino djetinstvo i školovanje tokom drugog svjetskog rata između Zagreba i Trbovlja.",
            actionButtonText: null,
            negativeActionButtonText: null,
            parentId: "silva-uzorinac-e513d996",
            parentNavigationType: "SPIRITUS_DETAILS",
            itemId: "mala-silva-c2d2a022",
            itemNavigationType: "STORY_DETAILS",
            itemPayload: null,
            imageUrl: "/images/1642/story",
            flags: [],
          },
          {
            id: 397163,
            title: '"Zeko i potočić" ostat će zauvijek u našim srcima',
            subtitle: "Zdenka Vučković",
            placeholderText:
              "Nevjerojatan život pjevačke dive koja je otpjevala najpoznatiju hrvatsku dječju uspavanku.",
            actionButtonText: null,
            negativeActionButtonText: null,
            parentId: "zdenka-vuckovic-oblak-8b4a0739",
            parentNavigationType: "SPIRITUS_DETAILS",
            itemId: "-zeko-i-potocic-ostat-ce-uvijek-u-nasim-srcima-407d23b8",
            itemNavigationType: "STORY_DETAILS",
            itemPayload: null,
            imageUrl: "/images/1649/story",
            flags: [],
          },
          {
            id: 481974,
            title: "Kako je ban Jelačić vraćen na Trg?",
            subtitle: "Boris  Buzančić",
            placeholderText: "O prvom zagrebačkom gradonačelniku.\n",
            actionButtonText: null,
            negativeActionButtonText: null,
            parentId: "boris--buzancic-fbc7a62a",
            parentNavigationType: "SPIRITUS_DETAILS",
            itemId: "kako-je-ban-jelacic-vracen-na-trg-6b8e6911",
            itemNavigationType: "STORY_DETAILS",
            itemPayload: null,
            imageUrl: "/images/1664/story",
            flags: [],
          },
          {
            id: 74462,
            title: "Kupovao bi joj cvijeće",
            subtitle: "Miroslav Krleža",
            placeholderText: "Krleža je bio pravi kavalir.",
            actionButtonText: null,
            negativeActionButtonText: null,
            parentId: "miroslav-krleza-34967619",
            parentNavigationType: "SPIRITUS_DETAILS",
            itemId: "kupovao-bi-joj-cvijece-466d9d17",
            itemNavigationType: "STORY_DETAILS",
            itemPayload: null,
            imageUrl: "/images/1661/story",
            flags: [],
          },
          {
            id: 262091,
            title: "Kupovao bi joj cvijeće...",
            subtitle: "Bela Krleža",
            placeholderText: "Krleža je bio pravi kavalir",
            actionButtonText: null,
            negativeActionButtonText: null,
            parentId: "bela-krleza-45405da3",
            parentNavigationType: "SPIRITUS_DETAILS",
            itemId: "kupovao-bi-joj-cvijece-898f3f82",
            itemNavigationType: "STORY_DETAILS",
            itemPayload: null,
            imageUrl: "/images/1657/story",
            flags: [],
          },
        ],
        pageable: {
          sort: {
            sorted: false,
            unsorted: true,
            empty: true,
          },
          offset: 0,
          pageNumber: 0,
          pageSize: 10,
          paged: true,
          unpaged: false,
        },
        last: false,
        totalElements: 262,
        totalPages: 27,
        size: 10,
        number: 0,
        sort: {
          sorted: false,
          unsorted: true,
          empty: true,
        },
        first: true,
        numberOfElements: 10,
        empty: false,
      },
    },
    {
      id: 3,
      viewType: "MEDIUM",
      title: "Teme",
      state: null,
      subtitle: null,
      flags: ["CATEGOIRES_SECTION"],
      listPayload: null,
      version: "1",
      items: {
        content: [
          {
            id: 33,
            title: "Biografija",
            subtitle: null,
            placeholderText: null,
            actionButtonText: null,
            negativeActionButtonText: null,
            parentId: null,
            parentNavigationType: null,
            itemId: "33",
            itemNavigationType: "STORIES_LIST_CATEGORY",
            itemPayload: null,
            imageUrl: "/images/574/tag",
            flags: null,
          },
          {
            id: 8,
            title: "Znameniti",
            subtitle: null,
            placeholderText: null,
            actionButtonText: null,
            negativeActionButtonText: null,
            parentId: null,
            parentNavigationType: null,
            itemId: "8",
            itemNavigationType: "STORIES_LIST_CATEGORY",
            itemPayload: null,
            imageUrl: "/images/565/tag",
            flags: null,
          },
          {
            id: 31,
            title: "Ljubav",
            subtitle: null,
            placeholderText: null,
            actionButtonText: null,
            negativeActionButtonText: null,
            parentId: null,
            parentNavigationType: null,
            itemId: "31",
            itemNavigationType: "STORIES_LIST_CATEGORY",
            itemPayload: null,
            imageUrl: "/images/566/tag",
            flags: null,
          },
          {
            id: 39,
            title: "Anegdote",
            subtitle: null,
            placeholderText: null,
            actionButtonText: null,
            negativeActionButtonText: null,
            parentId: null,
            parentNavigationType: null,
            itemId: "39",
            itemNavigationType: "STORIES_LIST_CATEGORY",
            itemPayload: null,
            imageUrl: "/images/564/tag",
            flags: null,
          },
          {
            id: 34,
            title: "Obitelj",
            subtitle: null,
            placeholderText: null,
            actionButtonText: null,
            negativeActionButtonText: null,
            parentId: null,
            parentNavigationType: null,
            itemId: "34",
            itemNavigationType: "STORIES_LIST_CATEGORY",
            itemPayload: null,
            imageUrl: "/images/567/tag",
            flags: null,
          },
          {
            id: 40,
            title: "Motivacija",
            subtitle: null,
            placeholderText: null,
            actionButtonText: null,
            negativeActionButtonText: null,
            parentId: null,
            parentNavigationType: null,
            itemId: "40",
            itemNavigationType: "STORIES_LIST_CATEGORY",
            itemPayload: null,
            imageUrl: "/images/568/tag",
            flags: null,
          },
          {
            id: 41,
            title: "Sport",
            subtitle: null,
            placeholderText: null,
            actionButtonText: null,
            negativeActionButtonText: null,
            parentId: null,
            parentNavigationType: null,
            itemId: "41",
            itemNavigationType: "STORIES_LIST_CATEGORY",
            itemPayload: null,
            imageUrl: "/images/569/tag",
            flags: null,
          },
          {
            id: 42,
            title: "Umjetnost",
            subtitle: null,
            placeholderText: null,
            actionButtonText: null,
            negativeActionButtonText: null,
            parentId: null,
            parentNavigationType: null,
            itemId: "42",
            itemNavigationType: "STORIES_LIST_CATEGORY",
            itemPayload: null,
            imageUrl: "/images/570/tag",
            flags: null,
          },
          {
            id: 32,
            title: "Rat",
            subtitle: null,
            placeholderText: null,
            actionButtonText: null,
            negativeActionButtonText: null,
            parentId: null,
            parentNavigationType: null,
            itemId: "32",
            itemNavigationType: "x",
            itemPayload: null,
            imageUrl: "/images/571/tag",
            flags: null,
          },
          {
            id: 36,
            title: "Hobi",
            subtitle: null,
            placeholderText: null,
            actionButtonText: null,
            negativeActionButtonText: null,
            parentId: null,
            parentNavigationType: null,
            itemId: "36",
            itemNavigationType: "STORIES_LIST_CATEGORY",
            itemPayload: null,
            imageUrl: "/images/573/tag",
            flags: null,
          },
        ],
        pageable: {
          sort: {
            sorted: false,
            unsorted: true,
            empty: true,
          },
          offset: 0,
          pageNumber: 0,
          pageSize: 10,
          paged: true,
          unpaged: false,
        },
        last: false,
        totalElements: 11,
        totalPages: 2,
        size: 10,
        number: 0,
        sort: {
          sorted: false,
          unsorted: true,
          empty: true,
        },
        first: true,
        numberOfElements: 10,
        empty: false,
      },
    },
    {
      id: 13,
      viewType: "LARGE",
      title: "Vječni Spiritusi",
      state: null,
      subtitle: null,
      flags: ["ETERNALS_SECTION"],
      listPayload: null,
      version: "1",
      items: {
        content: [
          {
            id: 83468,
            title: "Pero Magdić",
            subtitle: "03 Jul 1863 — 22 Sep 1922",
            placeholderText: "Veliki domoljub, pisac, političar i sportaš!",
            actionButtonText: null,
            negativeActionButtonText: null,
            parentId: null,
            parentNavigationType: null,
            itemId: "pero-magdic-b010ef2a",
            itemNavigationType: "SPIRITUS_DETAILS",
            itemPayload: null,
            imageUrl: "/images/89478/spiritus",
            flags: [],
          },
          {
            id: 66046,
            title: "Nikola Tesla",
            subtitle: "10 Jul 1856 — 07 Jan 1943",
            placeholderText:
              "Nije mi žao što su ukrali moje ideje, već što nisu imali svoje.",
            actionButtonText: null,
            negativeActionButtonText: null,
            parentId: null,
            parentNavigationType: null,
            itemId: "nikola-tesla-e8c4fc00",
            itemNavigationType: "SPIRITUS_DETAILS",
            itemPayload: null,
            imageUrl: "/images/89561/spiritus",
            flags: [],
          },
          {
            id: 74373,
            title: "Dino Dvornik",
            subtitle: "20 Aug 1964 — 07 Sep 2008",
            placeholderText:
              "Ma ne triba meni ništa lova, samo da ja pivan i da sviran, i da iman dobru glazbu!!\n",
            actionButtonText: null,
            negativeActionButtonText: null,
            parentId: null,
            parentNavigationType: null,
            itemId: "dino-dvornik-65a2e4af",
            itemNavigationType: "SPIRITUS_DETAILS",
            itemPayload: null,
            imageUrl: "/images/89895/spiritus",
            flags: [],
          },
          {
            id: 264073,
            title: "MISLAV MARIČEVIĆ",
            subtitle: "03 Oct 1974 — 14 Oct 2007",
            placeholderText:
              "Ovaj Spiritus još nema svoga Čuvara uspomene. Pošalji zahtjev kako bi postao Čuvar i sačuvao sjećanje!",
            actionButtonText: null,
            negativeActionButtonText: null,
            parentId: null,
            parentNavigationType: null,
            itemId: "mislav-maricevic-3cb2c0c5",
            itemNavigationType: "SPIRITUS_DETAILS",
            itemPayload: null,
            imageUrl: null,
            flags: [],
          },
        ],
        pageable: {
          sort: {
            sorted: false,
            unsorted: true,
            empty: true,
          },
          offset: 0,
          pageNumber: 0,
          pageSize: 10,
          paged: true,
          unpaged: false,
        },
        last: true,
        totalElements: 4,
        totalPages: 1,
        size: 10,
        number: 0,
        sort: {
          sorted: false,
          unsorted: true,
          empty: true,
        },
        first: true,
        numberOfElements: 4,
        empty: false,
      },
    },
    {
      id: 10,
      viewType: "BANNER",
      title: null,
      state: null,
      subtitle: null,
      flags: ["BANNERS_SECTION"],
      listPayload: null,
      version: "1",
      items: {
        content: [
          {
            id: 6,
            title: "Prijavite se ili izradite račun!",
            subtitle: "Sačuvaj uspomene o voljenima.",
            placeholderText: null,
            actionButtonText: "Izradi račun",
            negativeActionButtonText: "Login",
            parentId: "null",
            parentNavigationType: null,
            itemId: "null",
            itemNavigationType: "REGISTER_ACCOUNT",
            itemPayload: null,
            imageUrl: null,
            flags: [],
          },
        ],
        pageable: {
          sort: {
            sorted: false,
            unsorted: true,
            empty: true,
          },
          offset: 0,
          pageNumber: 0,
          pageSize: 1,
          paged: true,
          unpaged: false,
        },
        last: true,
        totalElements: 1,
        totalPages: 1,
        size: 1,
        number: 0,
        sort: {
          sorted: false,
          unsorted: true,
          empty: true,
        },
        first: true,
        numberOfElements: 1,
        empty: false,
      },
    },
    {
      id: 6,
      viewType: "LARGE",
      title: "Istaknute priče",
      state: null,
      subtitle: "Istraži najljepše i najzanimljivije priče.",
      flags: ["SHOW_ALL", "FEATURED_STORIES"],
      listPayload: null,
      version: "1",
      items: {
        content: [
          {
            id: 99,
            title: "The Book Thief",
            subtitle: "Mirko Kovač",
            placeholderText: "Why did the famous writer steal books as a kid?",
            actionButtonText: null,
            negativeActionButtonText: null,
            parentId: "mirko-kovac-573f08b0",
            parentNavigationType: "SPIRITUS_DETAILS",
            itemId: "the-book-thief-3aa70fab",
            itemNavigationType: "STORY_DETAILS",
            itemPayload: null,
            imageUrl: "/images/626/story",
            flags: ["PUBLIC", "FEATURED"],
          },
          {
            id: 121,
            title: "A Small Town Boy's Ambition",
            subtitle: "Dino Škrapić",
            placeholderText:
              "Dino's incredible ambition to this day inspires Rovinj's youth.",
            actionButtonText: null,
            negativeActionButtonText: null,
            parentId: "dino-skrapic-f1edf128",
            parentNavigationType: "SPIRITUS_DETAILS",
            itemId: "a-small-town-boy-s-ambition-9e8275eb",
            itemNavigationType: "STORY_DETAILS",
            itemPayload: null,
            imageUrl: "/images/607/story",
            flags: ["FEATURED", "PRIVATE"],
          },
          {
            id: 169,
            title: "Beren and Lúthien",
            subtitle: "John Ronald Reuel Tolkien",
            placeholderText:
              "– May you each be a light for one another when all other lights go out. –",
            actionButtonText: null,
            negativeActionButtonText: null,
            parentId: "john-ronald reuel-tolkien-8c6af4aa",
            parentNavigationType: "SPIRITUS_DETAILS",
            itemId: "beren-and-luthien-2800fedf",
            itemNavigationType: "STORY_DETAILS",
            itemPayload: null,
            imageUrl: "/images/683/story",
            flags: ["FEATURED", "PRIVATE"],
          },
          {
            id: 202,
            title: 'Meeting „Mrs. President"',
            subtitle: "Stan Lee",
            placeholderText:
              "Unforgetable encounter between the First Lady and clumsy Stan. ",
            actionButtonText: null,
            negativeActionButtonText: null,
            parentId: "stan-lee-0010755f",
            parentNavigationType: "SPIRITUS_DETAILS",
            itemId: "meeting-mrs-president-5d7696b3",
            itemNavigationType: "STORY_DETAILS",
            itemPayload: null,
            imageUrl: "/images/705/story",
            flags: ["FEATURED", "PRIVATE"],
          },
          {
            id: 224,
            title: "The Enigma",
            subtitle: "Alan Turing",
            placeholderText: "How did Turing decipher Nazi's secret code?",
            actionButtonText: null,
            negativeActionButtonText: null,
            parentId: "alan-turing-f61f9e37",
            parentNavigationType: "SPIRITUS_DETAILS",
            itemId: "the-enigma-1651d485",
            itemNavigationType: "STORY_DETAILS",
            itemPayload: null,
            imageUrl: "/images/720/story",
            flags: ["FEATURED", "PRIVATE"],
          },
        ],
        pageable: {
          sort: {
            sorted: false,
            unsorted: true,
            empty: true,
          },
          offset: 0,
          pageNumber: 0,
          pageSize: 10,
          paged: true,
          unpaged: false,
        },
        last: true,
        totalElements: 5,
        totalPages: 1,
        size: 10,
        number: 0,
        sort: {
          sorted: false,
          unsorted: true,
          empty: true,
        },
        first: true,
        numberOfElements: 5,
        empty: false,
      },
    },
    {
      id: 11,
      viewType: "ENABLE_LOCATION_BANNER",
      title: null,
      state: null,
      subtitle: null,
      flags: ["BANNERS_SECTION"],
      listPayload: null,
      version: "1",
      items: {
        content: [
          {
            id: 7,
            title: null,
            subtitle:
              "Uključite geolokaciju za prikaz Aleje sjećanja i groblja u Vašoj blizini.",
            placeholderText: null,
            actionButtonText: "Uključite lokaciju",
            negativeActionButtonText: "Ne sada",
            parentId: "null",
            parentNavigationType: null,
            itemId: "null",
            itemNavigationType: "ENABLE_LOCATION",
            itemPayload: null,
            imageUrl: null,
            flags: [],
          },
        ],
        pageable: {
          sort: {
            sorted: false,
            unsorted: true,
            empty: true,
          },
          offset: 0,
          pageNumber: 0,
          pageSize: 1,
          paged: true,
          unpaged: false,
        },
        last: true,
        totalElements: 1,
        totalPages: 1,
        size: 1,
        number: 0,
        sort: {
          sorted: false,
          unsorted: true,
          empty: true,
        },
        first: true,
        numberOfElements: 1,
        empty: false,
      },
    },
    {
      id: 7,
      viewType: "MEMORY_WALK",
      title: "Aleja sjećanja",
      state: null,
      subtitle:
        "Otkrij lijepe i zanimljive priče oko sebe. Pretraži obližnja groblja.",
      flags: ["SHOW_ALL", "MEMORY_WALK_SECTION"],
      listPayload: null,
      version: "2",
      items: {
        content: [
          {
            id: 48,
            title: "ZAGREB 🇭🇷",
            subtitle: "Mirogoj",
            placeholderText: null,
            actionButtonText: "Enter Memory Walk",
            negativeActionButtonText: "About",
            parentId: null,
            parentNavigationType: null,
            itemId: "48",
            itemNavigationType: "MEMORY_WALK",
            itemPayload:
              "{  'numberOfSpiritus':'244.9k',  'numberOfFeaturedSpiritus':15 }",
            imageUrl: "/images/34/graveyard",
            flags: null,
          },
          {
            id: 31,
            title: "VUKOVAR 🇭🇷",
            subtitle: "Vukovar - staro katoličko groblje",
            placeholderText: null,
            actionButtonText: "Enter Memory Walk",
            negativeActionButtonText: "About",
            parentId: null,
            parentNavigationType: null,
            itemId: "31",
            itemNavigationType: "MEMORY_WALK",
            itemPayload:
              "{  'numberOfSpiritus':'6.2k',  'numberOfFeaturedSpiritus':0 }",
            imageUrl: "/images/3/graveyard",
            flags: null,
          },
          {
            id: 30,
            title: "VUKOVAR 🇭🇷",
            subtitle: "Sotin - pravoslavno groblje",
            placeholderText: null,
            actionButtonText: "Enter Memory Walk",
            negativeActionButtonText: "About",
            parentId: null,
            parentNavigationType: null,
            itemId: "30",
            itemNavigationType: "MEMORY_WALK",
            itemPayload:
              "{  'numberOfSpiritus':'300+',  'numberOfFeaturedSpiritus':0 }",
            imageUrl: "/images/4/graveyard",
            flags: null,
          },
          {
            id: 32,
            title: "VUKOVAR 🇭🇷",
            subtitle: "Vukovar - pravoslavno groblje",
            placeholderText: null,
            actionButtonText: "Enter Memory Walk",
            negativeActionButtonText: "About",
            parentId: null,
            parentNavigationType: null,
            itemId: "32",
            itemNavigationType: "MEMORY_WALK",
            itemPayload:
              "{  'numberOfSpiritus':'2.0k',  'numberOfFeaturedSpiritus':0 }",
            imageUrl: "/images/1/graveyard",
            flags: null,
          },
          {
            id: 28,
            title: "VUKOVAR 🇭🇷",
            subtitle: "Lipovača",
            placeholderText: null,
            actionButtonText: "Enter Memory Walk",
            negativeActionButtonText: "About",
            parentId: null,
            parentNavigationType: null,
            itemId: "28",
            itemNavigationType: "MEMORY_WALK",
            itemPayload:
              "{  'numberOfSpiritus':'300+',  'numberOfFeaturedSpiritus':0 }",
            imageUrl: "/images/6/graveyard",
            flags: null,
          },
          {
            id: 27,
            title: "VUKOVAR 🇭🇷",
            subtitle: "Novo groblje Dubrava",
            placeholderText: null,
            actionButtonText: "Enter Memory Walk",
            negativeActionButtonText: "About",
            parentId: null,
            parentNavigationType: null,
            itemId: "27",
            itemNavigationType: "MEMORY_WALK",
            itemPayload:
              "{  'numberOfSpiritus':'11.5k',  'numberOfFeaturedSpiritus':0 }",
            imageUrl: "/images/7/graveyard",
            flags: null,
          },
          {
            id: 29,
            title: "VUKOVAR 🇭🇷",
            subtitle: "Sotin - katoličko groblje",
            placeholderText: null,
            actionButtonText: "Enter Memory Walk",
            negativeActionButtonText: "About",
            parentId: null,
            parentNavigationType: null,
            itemId: "29",
            itemNavigationType: "MEMORY_WALK",
            itemPayload:
              "{  'numberOfSpiritus':'1.0k',  'numberOfFeaturedSpiritus':0 }",
            imageUrl: "/images/5/graveyard",
            flags: null,
          },
        ],
        pageable: {
          sort: {
            sorted: false,
            unsorted: true,
            empty: true,
          },
          offset: 0,
          pageNumber: 0,
          pageSize: 10,
          paged: true,
          unpaged: false,
        },
        last: true,
        totalElements: 7,
        totalPages: 1,
        size: 10,
        number: 0,
        sort: {
          sorted: false,
          unsorted: true,
          empty: true,
        },
        first: true,
        numberOfElements: 7,
        empty: false,
      },
    },
  ],
};
