name: Deploy Production

# production deploymnet is manual
on:
  workflow_dispatch:

jobs:
  remote-build:
    runs-on: ubuntu-latest
    steps:
      - name: Build container on remote host
        uses: appleboy/ssh-action@master
        env:
          NEXT_JWT_SECRET: ${{ secrets.NEXT_JWT_SECRET }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          NEXT_API_URL: https://walk.spiritusapp.com
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          key: ${{ secrets.PROD_KEY }}
          envs: NEXT_API_URL,NEXT_JWT_SECRET,NEXTAUTH_SECRET
          script: |
            [ -d webapp ] && echo "Repo already cloned -- skipping" || git clone git@github.com:Spiritus-Memoria-Organization/webapp.git
            cd webapp
            echo "## Pulling latest changes..."
            git pull --ff-only
            echo "## Building new containers"
            echo -e "NEXT_API_URL=$NEXT_API_URL\nNEXT_JWT_SECRET=$NEXT_JWT_SECRET\nNEXTAUTH_SECRET=$NEXTAUTH_SECRET" > .env
            docker compose build
            echo "## BUILD DONE ##"

  deploy:
    runs-on: ubuntu-latest
    needs: remote-build
    steps:
      - name: Deploy Production
        uses: appleboy/ssh-action@master
        env:
          NEXT_JWT_SECRET: ${{ secrets.NEXT_JWT_SECRET }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          NEXT_API_URL: https://walk.spiritusapp.com
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          key: ${{ secrets.PROD_KEY }}
          envs: NEXT_API_URL,NEXT_JWT_SECRET,NEXTAUTH_SECRET
          script: |
            cd webapp
            echo "## Building and starting containers"
            echo -e "NEXT_API_URL=$NEXT_API_URL\nNEXT_JWT_SECRET=$NEXT_JWT_SECRET\nNEXTAUTH_SECRET=$NEXTAUTH_SECRET" > .env
            docker compose up --build spiritus-web -d
            echo "## DEPLOY DONE ##"
