name: Deploy Production

# production deploymnet is manual
on:
  workflow_dispatch:

jobs:
  remote-build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Production
        uses: appleboy/ssh-action@master
        env:
          NEXT_JWT_SECRET: ${{ secrets.NEXT_JWT_SECRET }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          NEXT_API_URL: https://walk.spiritusapp.com
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          key: ${{ secrets.PROD_KEY }}
          envs: NEXT_API_URL,NEXT_JWT_SECRET,NEXTAUTH_SECRET
          script: |
            [ -d webapp ] && echo "Repo already cloned -- skipping" || git clone git@github.com:Spiritus-Memoria-Organization/webapp.git
            cd webapp
            echo "Pulling latest changes..."
            git pull --ff-only
            echo "Target API URL: $NEXT_API_URL"
            echo "Build new container"
            docker compose build
            echo "BUILD DONE"
  deploy:
    runs-on: ubuntu-latest
    needs: remote-build
    steps:
      - name: Deploy to Production
        uses: appleboy/ssh-action@master
        env:
          NEXT_JWT_SECRET: ${{ secrets.NEXT_JWT_SECRET }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          NEXT_API_URL: https://walk.spiritusapp.com
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          key: ${{ secrets.PROD_KEY }}
          envs: NEXT_API_URL,NEXT_JWT_SECRET,NEXTAUTH_SECRET
          script: |
            whoami
            echo "sve radi - zasad"
            [ -d webapp ] && echo "Repo already cloned -- skipping" || git clone git@github.com:Spiritus-Memoria-Organization/webapp.git
            cd webapp
            echo "Pulling latest changes..."
            git pull --ff-only
            echo "Target API URL: $NEXT_API_URL"
            echo "Build and start new container"
            docker compose up --build spiritus-web -d
            echo "DEPLOY DONE"
