name: Stop Staging

on:
  workflow_dispatch:

jobs:
  stop-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Stop all containers on staging host
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.STAGING_USERNAME }}
          key: ${{ secrets.STAGING_KEY }}
          script: |
            cd webapp
            docker compose stop
